baseURL = "https://sharma-abhi9av.github.io/"
languageCode = "en-us"
title = "Abhinav Sharma"
theme = "PaperMod"

[pagination]
pagerSize = 5

[params]
defaultTheme = "dark"
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowWordCount = true
ShowToc = true

description = "Cybersecurity | Red Team | Active Directory | CTF Writeups"

[params.homeInfoParams]
Title = "Abhinav Sharma"
Content = """
Cybersecurity enthusiast focused on offensive security, Active Directory exploitation, and real-world attack paths.

This blog documents my practical learning journey through labs, CTFs, and research.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/sharma-abhi9av"

[params.assets]
disableHLJS = false
