site_name: "Abhinav Sharma"
site_url: https://sharma-abhi9av.github.io/

use_directory_urls: false

theme:
  name: material
  icon:
    logo: material/github
  favicon: assets/mikey.jpeg
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to Dark Mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to Light Mode
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - awesome-pages

extra:
  generator: false

docs_dir: docs

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
